import type { Vehicle } from "@/lib/types"

export const vehicles: Vehicle[] = [
  {
    id: "1",
    make: "Toyota",
    model: "Camry",
    year: 2023,
    trim: "XSE V6",
    price: 35999,
    mileage: 5230,
    exteriorColor: "Midnight Black Metallic",
    interiorColor: "Black",
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "3.5L V6",
    vin: "4T1BZ1HK1NU123456",
    stockNumber: "TC23001",
    description:
      "This 2023 Toyota Camry XSE V6 offers a perfect blend of luxury, performance, and reliability. With its sleek Midnight Black Metallic exterior and premium black interior, this sedan stands out on the road. The powerful 3.5L V6 engine delivers an exhilarating driving experience while maintaining excellent fuel efficiency. Loaded with advanced safety features and modern technology, this Camry provides both comfort and peace of mind for all your journeys.",
    features: [
      "Leather Seats",
      "Navigation System",
      "Panoramic Sunroof",
      "Blind Spot Monitoring",
      "Apple CarPlay & Android Auto",
      "JBL Premium Audio",
      "Adaptive Cruise Control",
      "Lane Departure Warning",
      "360° Camera System",
      "Heated & Ventilated Front Seats",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    featured: true,
  },
  {
    id: "2",
    make: "Honda",
    model: "Accord",
    year: 2022,
    trim: "Touring 2.0T",
    price: 32495,
    mileage: 12750,
    exteriorColor: "Platinum White Pearl",
    interiorColor: "Ivory",
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "2.0L Turbo I-4",
    vin: "1HGCV2F98NA123789",
    stockNumber: "HA22015",
    description:
      "Experience luxury and performance with this 2022 Honda Accord Touring 2.0T. The elegant Platinum White Pearl exterior paired with a sophisticated Ivory interior creates a stunning visual appeal. Powered by a responsive 2.0L Turbocharged engine, this Accord delivers impressive acceleration and handling. Featuring Honda's renowned reliability and packed with premium amenities, this sedan offers exceptional value for discerning drivers seeking both comfort and efficiency.",
    features: [
      "Leather-Trimmed Seats",
      "Head-Up Display",
      "Wireless Phone Charger",
      "Honda Sensing Safety Suite",
      "Bose Premium Sound System",
      "Heated & Ventilated Front Seats",
      "Heated Rear Seats",
      "Wi-Fi Hotspot Capability",
      "Rain-Sensing Wipers",
      "Remote Engine Start",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    featured: false,
  },
  {
    id: "3",
    make: "Tesla",
    model: "Model Y",
    year: 2023,
    trim: "Performance",
    price: 62990,
    mileage: 3450,
    exteriorColor: "Deep Blue Metallic",
    interiorColor: "Black",
    fuelType: "Electric",
    transmission: "Automatic",
    engine: "Dual Motor AWD",
    vin: "5YJYGDEE3MF123456",
    stockNumber: "TY23007",
    description:
      "Embrace the future of driving with this 2023 Tesla Model Y Performance. This all-electric SUV combines versatility, performance, and cutting-edge technology in one stunning package. The Deep Blue Metallic exterior and premium Black interior create a sophisticated aesthetic. With its Dual Motor All-Wheel Drive system, this Model Y delivers exhilarating acceleration and impressive range. Featuring Tesla's advanced Autopilot capabilities and spacious interior, this vehicle offers both excitement and practicality for modern drivers.",
    features: [
      "Autopilot",
      "Full Self-Driving Capability",
      "Glass Roof",
      "Premium Audio System",
      "Heated Seats (All Rows)",
      '21" Überturbine Wheels',
      "Performance Brakes",
      "Premium Connectivity",
      "Supercharging Capability",
      "Over-the-air Updates",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    featured: true,
  },
  {
    id: "4",
    make: "Ford",
    model: "F-150",
    year: 2022,
    trim: "Lariat SuperCrew",
    price: 54750,
    mileage: 15680,
    exteriorColor: "Rapid Red Metallic",
    interiorColor: "Black/Mesa",
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "3.5L EcoBoost V6",
    vin: "1FTFW1E82NFA78901",
    stockNumber: "FF22032",
    description:
      "This 2022 Ford F-150 Lariat SuperCrew combines rugged capability with refined comfort. The striking Rapid Red Metallic exterior and premium Black/Mesa interior create a bold yet sophisticated appearance. Powered by the robust 3.5L EcoBoost V6 engine, this truck delivers impressive towing capacity and performance. With its spacious cabin, advanced technology features, and versatile bed, this F-150 is ready to tackle both work demands and family adventures with equal ease.",
    features: [
      "Leather-Trimmed Seats",
      'SYNC 4 with 12" Touchscreen',
      "Pro Power Onboard Generator",
      "B&O Sound System",
      "360-Degree Camera",
      "Power Tailgate",
      "Trailer Tow Package",
      "Lane-Keeping System",
      "Adaptive Cruise Control",
      "FordPass Connect",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    featured: false,
  },
  {
    id: "5",
    make: "BMW",
    model: "X5",
    year: 2023,
    trim: "xDrive40i",
    price: 68900,
    mileage: 7890,
    exteriorColor: "Mineral White Metallic",
    interiorColor: "Cognac",
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "3.0L Turbo I-6",
    vin: "5UXCR6C03N9D12345",
    stockNumber: "BX23009",
    description:
      "Experience luxury and performance with this 2023 BMW X5 xDrive40i. The elegant Mineral White Metallic exterior combined with the rich Cognac interior creates a stunning visual presence. Powered by BMW's refined 3.0L Turbocharged inline-six engine, this SAV delivers a perfect balance of power and efficiency. With its advanced technology, premium materials, and dynamic driving characteristics, this X5 offers an exceptional driving experience for those who demand the very best in luxury and performance.",
    features: [
      "Premium Leather Upholstery",
      "Panoramic Moonroof",
      "Harman Kardon Surround Sound",
      "Live Cockpit Professional",
      "Driving Assistance Professional",
      "Comfort Access",
      "4-Zone Climate Control",
      "Heated & Ventilated Front Seats",
      "Wireless Charging",
      "Parking Assistant Plus",
    ],
    images: [
      "/bmw/1.png",
      "/bmw/2.png",
      "/bmw/3.png",
      "/bmw/4.png",
      "/bmw/5.png",
      "/bmw/6.png",
      "/bmw/7.png",
      "/bmw/8.png",
    ],
    featured: true,
  },
]
